"""Generate a self-contained illustrated review and reproducibility hash manifest."""
import base64,hashlib,html,importlib.metadata,json,pathlib,platform,subprocess
ROOT=pathlib.Path(__file__).resolve().parent
versions={'python':platform.python_version(),'gcc':subprocess.check_output(['gcc','--version'],text=True).splitlines()[0]}
for name in ['cadquery','cadquery-ocp','mujoco','numpy','scipy','trimesh','python-fcl','matplotlib','Pillow']:
 versions[name]=importlib.metadata.version(name)
(ROOT/'checks/software_versions.json').write_text(json.dumps(versions,indent=2))
import xml.etree.ElementTree as ET
mesh_names=[e.get('file') for e in ET.parse(ROOT/'simulation/balanced.xml').getroot().findall('./asset/mesh') if not e.get('file').startswith('../')]
mesh_hashes=[]
for name in mesh_names:
 p=ROOT.parents[1]/'sim-model/assets/meshes'/name
 mesh_hashes.append({'path':'sim-model/assets/meshes/'+name,'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()})
(ROOT/'checks/source_mesh_hashes.json').write_text(json.dumps({'revision':'35ae7b3581ce36762bfddb00b8fc5e7c957ee7fa','retained_source_assets':mesh_hashes},indent=2))
props=json.loads((ROOT/'checks/mass_properties.json').read_text());cad=json.loads((ROOT/'checks/cad_roundtrip.json').read_text());results=json.loads((ROOT/'checks/contact_results.json').read_text())
captions={'assembly_front.png':'New base with original source upper meshes. Green hands and battery are allowances, not selected hardware.',
'assembly_side.png':'Side view: short mast, source-pattern cradles and low proposed drive battery.',
'assembly_parked.png':'Manual parking configuration. No automatic deployment or verified stow mechanism.',
'assembly_rear.png':'Rear review of the actual source mesh and new frame geometry.',
'base_detail.png':'Actual CAD base, including explicit axle seats and split torque clamps.',
'base_top.png':'Open deck and mounting layout; wiring and positive battery retention remain unresolved.',
'assembly_exploded.png':'Illustrative exploded placement, not a collision-checked operating configuration.',
'interface_sections.png':'Exact STEP sections: clamp bore/split, source hole pattern and frame wall geometry.',
'mass_budget.png':'Source upper masses plus CAD metal volume and explicit purchased-part allowances.',
'balance_evidence.png':'Computed balance traces; physical validation and a hardware estimator are not delivered.',
'recovery_envelope.png':'Finite simulated recovery conditions; this is not a certified operating envelope.',
'driving_evidence.png':'Combined drive, yaw and arm reach: balance/heading pass but 30 mm position criterion fails.'}
def im(name):return 'data:image/png;base64,'+base64.b64encode((ROOT/'visuals'/name).read_bytes()).decode()
def fig(name):return f'<figure><img loading="lazy" src="{im(name)}" alt="{html.escape(captions[name])}"><figcaption>{html.escape(captions[name])}</figcaption></figure>'
rows=[]
for i,r in enumerate(results,1):
 condition=('manual parking' if r['parked'] else 'power cut at 1 s' if r['poweroff_s'] is not None else 'drive + yaw + reach' if r['driving'] else 'arm reach + COM feedback' if r['adaptive_com'] else 'arm reach, fixed-body feedback' if r['articulated'] else f"{r['torso_push_N_for_150ms']} N torso push" if r['torso_push_N_for_150ms'] else f"{r['initial_deg']}° lean, μ={r['friction']}, {r['torque_Nm_each']} Nm/wheel")
 status='pass' if r['recovered'] else 'fail'
 rows.append(f'<tr><td>{i:02}</td><td>{html.escape(condition)}</td><td class="{status}">{status.upper()}</td><td>{r["duration_s"]:.3f}</td><td>{r["final_COM_pitch_deg"]:.4f}</td></tr>')
body=f'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Asimov balancing body — engineering review</title>
<style>:root{{color-scheme:light}}*{{box-sizing:border-box}}body{{margin:0;background:#eef2f3;color:#18303c;font:17px/1.6 system-ui,sans-serif}}main{{max-width:1150px;margin:auto;padding:36px 24px 70px}}h1{{font-size:clamp(30px,5vw,52px);line-height:1.1;max-width:850px;margin:12px 0 24px}}h2{{margin-top:42px;font-size:27px}}p{{max-width:890px}}.tag{{font-size:13px;letter-spacing:1.5px;text-transform:uppercase;color:#09675f;font-weight:700}}.hero{{display:grid;grid-template-columns:1.1fr 1fr;gap:28px;align-items:center}}.hero img{{width:100%;max-height:620px;object-fit:contain;background:#cdd4d5;border-radius:14px}}.metrics{{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:25px 0}}.metrics div{{background:white;border-radius:12px;padding:18px}}strong.number{{font-size:28px;display:block}}.note{{padding:17px 22px;background:#fff2d9;border-left:4px solid #b86d28;border-radius:6px}}.gallery{{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px}}figure{{margin:0;background:white;padding:10px;border-radius:12px;overflow:hidden}}figure img{{width:100%;max-height:650px;object-fit:contain}}figcaption{{font-size:14px;padding:10px;color:#425964}}.wide{{grid-column:1/-1}}table{{width:100%;border-collapse:collapse;background:white;font-size:14px}}th,td{{padding:10px;text-align:left;border-bottom:1px solid #dbe4e7}}th{{background:#dbe9e7}}.pass{{color:#08684c;font-weight:700}}.fail{{color:#9b351f;font-weight:700}}a{{color:#006a73}}footer{{border-top:1px solid #b7c9cf;margin-top:40px;padding-top:20px;font-size:14px}}@media(max-width:720px){{.hero,.gallery{{grid-template-columns:1fr}}.metrics{{grid-template-columns:repeat(2,1fr)}}main{{padding:25px 14px}}table{{font-size:12px}}th,td{{padding:6px}}}}
</style><main><div class="tag">CAD prototype · 2026-10-07 · source pinned</div><h1>Asimov upper body.<br>A smaller balancing base.</h1>
<div class="hero"><div><p>A fresh integrated model: original Asimov upper-body geometry and inertials on a new frame with 160 mm wheels. The rejected body layouts are discarded.</p><p>The load path, combined center of mass, wheel torque and arm motion are connected in one model. It remains a review prototype: hardware interfaces, thermal ratings and procurement are unresolved.</p><div class="note"><b>Cost is unquoted.</b> Neither a $100, $200 nor $500 complete build is supported. Green blocks are declared allowances. Wheel shapes are envelopes.</div></div><img src="{im('assembly_front.png')}" alt="New CAD base with source Asimov upper body"></div>
<div class="metrics"><div><strong class="number">{props['total_mass_kg']:.2f} kg</strong>Modeled complete mass</div><div><strong class="number">160 mm</strong>Wheel diameter</div><div><strong class="number">400 mm</strong>Wheel center spacing</div><div><strong class="number">{cad['assembly_solids']}</strong>Valid new CAD solids</div></div>
<h2>What the tests actually show</h2><p>At the assumed 6 Nm per wheel and floor friction μ=0.6, the 3D model recovers tested 2°, 5°, 10° and 15° leans. These research recoveries bypass the narrower candidate C fault guard and may exceed normal travel speed. With manual parking supports it stays upright without motor torque. Unparked power loss reaches 45° in roughly 0.85 seconds after the cut.</p><p>Fixed-body feedback drifts about 421 mm during the slow arm reach. Joint-dependent COM feedback reduces final drift to about 0.16 mm in simulation. The combined drive/turn/reach test stays balanced and tracks heading but misses its 30 mm path criterion by 4.37 mm at eight seconds.</p><table><thead><tr><th>Case</th><th>3D contact condition</th><th>Criterion</th><th>Time (s)</th><th>Final COM pitch (°)</th></tr></thead><tbody>{''.join(rows)}</tbody></table>
<h2>Where it can break or lose balance</h2><p>An assumed 12 mm shaft and 6 mm deck fail the selected structural margins. The model uses 14 mm and 8 mm, with conditional calculated margins. Clamp friction, preload, welded material properties and the source pelvis case capacity still require physical proof. Two full-range shoulder-yaw poses intersect source meshes. Low traction and excessive control delay cause recovery failures.</p><h2>Software that needs to change</h2><p>The shipped biped policy must be replaced or bypassed in a dedicated wheeled mode. This package contains an independent compiled balance core, an articulated COM-feedback experiment, exact source serial codecs and a review-only FOC patch for torque control, independent wheels and reduced command lag. Local IMU/encoder drivers, sensor fusion, deterministic scheduling, torque calibration and a supported fault/parking state machine are not yet implemented on hardware.</p>
<h2>12 engineering images from the delivered geometry and results</h2><div class="gallery">{''.join(fig(n) for n in captions)}</div>
<h2>Review files</h2><p><a href="README.md">Engineering README: requirements, calculations, tolerances and blockers</a><br><a href="cad/concept/new_base.step">18-solid STEP base</a> · <a href="cad/build.py">Editable CadQuery model</a> · <a href="parameters.json">Parameters</a><br><a href="parts_list.csv">35-row mass BOM</a> · <a href="hardware_procurement.csv">81-row source hardware / procurement register</a> · <a href="checks/physical_pairwise_plan.json">Physical test plan (not run)</a></p>
<footer>Sources: egc365/asimov-1 35ae7b3581ce36762bfddb00b8fc5e7c957ee7fa; hoverboard-firmware-hack-FOC 4f141cbc97b297e194fd58e56444bd0322f902ac. Original notices and licenses retained. No hardware actuation was performed. Geometry checks, numerical models and physical proof are different evidence stages.</footer></main></html>'''
(ROOT/'review.html').write_text(body)
files=sorted(p for p in ROOT.rglob('*') if p.is_file() and '__pycache__' not in p.parts and p.name!='SHA256SUMS.txt' and p.suffix not in ['.so','.pyc','.zip'])
(ROOT/'SHA256SUMS.txt').write_text(''.join(f'{hashlib.sha256(p.read_bytes()).hexdigest()}  {p.relative_to(ROOT).as_posix()}\n' for p in files))
print(json.dumps({'files_hashed':len(files),'images':len(captions),'review_bytes':(ROOT/'review.html').stat().st_size,'release':'CAD prototype; hardware blockers and driving accuracy failure retained'}))
